#version: '3.8'  # Remove this line as it's obsolete in Docker Compose v2

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: postgres        # Default database name
      POSTGRES_USER: postgres      # Default user
      POSTGRES_PASSWORD: postgres  # Default password
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: django_backend
    command: >
      sh -c "python manage.py migrate &&
             gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./vite-project
      dockerfile: Dockerfile
    container_name: vite_frontend
    # No need to expose port or keep the container running
    volumes:
      - ./vite-project/dist:/app/dist  # Optional: Remove if not needed
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx_proxy
    ports:
      - "80:80"  # Expose Nginx on host's port 80
    volumes:
      - ./vite-project/dist:/usr/share/nginx/html:ro  # Mount frontend build
      # If serving Django static/media files via Nginx, uncomment the following:
      # - ./backend/static:/app/static:ro
      # - ./backend/media:/app/media:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
