databases:
  - name: schoolwebsite  # The name of your Render database
    plan: free
    databaseName: school_9syr  # Name of the actual database
    user: rafael          # Database user name
    region: frankfurt

services:
  - type: web
    plan: free
    name: schoolwebsite    # Name of your service
    runtime: python
    buildCommand: "./build.sh"    # Your build script for React or static assets, if applicable
    startCommand: "python -m uvicorn backend.asgi:application -k uvicorn.workers.UvicornWorker"  # Django project directory here (backend)
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: schoolwebsite  # This connects the service to the Render database
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: ALLOWED_HOSTS
        value: "school-website-1-a2f6.onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://school-website-1-a2f6.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://school-website-1-a2f6.onrender.com"
      - key: DEBUG
        value: False  # Make sure the app is running in production mode