# Generated by Django 4.2.15 on 2024-08-28 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_delete_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_view_form', 'Can view form'), ('can_view_calendar', 'Can view calendar'), ('can_manage_users', 'Can manage users')]},
        ),
    ]
